import { existsSync } from "node:fs";
import { writeFile } from "node:fs/promises";
import { join, basename } from "node:path";
import type { AuditInput, ArtifactResult, RepoEvidence } from "../types.js";

// ── Template strings ──────────────────────────────────────────────────────────

const AGENTS_TEMPLATE = `\
# Agent Instructions — {{PROJECT_NAME}}

Generated by agent-harness on {{GENERATED_DATE}}.
Rename to \`AGENTS.md\` and customize before committing.

---

## Project Overview

<!-- Describe what this project does in 2–3 sentences. -->
<!-- Example: "This is a {{DETECTED_FRAMEWORK}} app that does X." -->

## Tech Stack

- Language: {{DETECTED_LANGUAGE}}
- Framework: {{DETECTED_FRAMEWORK}}

## Operating Rules

<!-- Define what the agent is and is not allowed to do. -->
- Always run \`npm test\` before marking a task done
- Do not modify database schema without explicit instruction
- Ask before deleting files

## Common Tasks

<!-- Describe the most frequent tasks agents perform in this repo. -->
- To add a new feature: ...
- To fix a bug: ...
- To run the project locally: ...

## Validation Commands

\`\`\`bash
npm run lint
npm run typecheck
npm test
\`\`\`

## Things to Avoid

<!-- List known pitfalls in this codebase. -->
- Do not edit generated files in \`dist/\`
- Do not commit \`.env\` files
`;

const CLAUDE_TEMPLATE = `\
# Claude Code Instructions — {{PROJECT_NAME}}

Generated by agent-harness on {{GENERATED_DATE}}.
Rename to \`CLAUDE.md\` and customize before committing.

---

## Project Overview

<!-- Describe this repo in 2–3 sentences for Claude Code. -->

## Working Rules

- Read \`AGENTS.md\` first if it exists
- Prefer small, reviewable changes
- Run validation commands before finishing a task
- Ask before making destructive or schema-changing edits

## Validation Commands

\`\`\`bash
npm run lint
npm run typecheck
npm test
\`\`\`

## Claude Code Settings

\`\`\`json
{
  "permissions": {
    "allow": ["Bash(npm run *)", "Read", "Edit", "Write"],
    "deny": ["Bash(rm -rf *)"]
  }
}
\`\`\`
`;

const VALIDATION_CHECKLIST_TEMPLATE = `\
# Validation Checklist — {{PROJECT_NAME}}

Generated by agent-harness on {{GENERATED_DATE}}.
Use this checklist before merging agent-assisted changes.

---

## Before Every Merge

- [ ] \`npm run lint\` passes with no errors
- [ ] \`npm run typecheck\` passes (if applicable)
- [ ] \`npm test\` passes (all tests green)
- [ ] No hardcoded credentials or secrets added
- [ ] No console.log / debug statements left in production code
- [ ] Changed files reviewed manually (not just AI-generated output)

## Before Deploying

- [ ] \`.env.example\` updated if new environment variables were added
- [ ] Database migrations tested locally (if applicable)
- [ ] Feature works on mobile viewport (if UI change)
- [ ] No new dependencies added without review

## Regression Checks

<!-- Add project-specific checks here. -->
- [ ] Core user flow works end-to-end
- [ ] ...
`;

const ARCHITECTURE_OUTLINE_TEMPLATE = `\
# Architecture Outline — {{PROJECT_NAME}}

Generated by agent-harness on {{GENERATED_DATE}}.
Fill in the sections below and commit as \`ARCHITECTURE.md\` or \`docs/architecture.md\`.

---

## What This Is

<!-- 2–3 sentences: what the system does and who uses it. -->

## Tech Stack

- Language: {{DETECTED_LANGUAGE}}
- Framework: {{DETECTED_FRAMEWORK}}
- Database: <!-- e.g. PostgreSQL, SQLite, none -->
- Hosting: <!-- e.g. Vercel, Railway, self-hosted -->

## Directory Structure

\`\`\`
<!-- Paste the output of \`ls -la\` or \`tree -L 2\` here -->
\`\`\`

## Key Files

| File/Dir | Purpose |
|---|---|
| <!-- path --> | <!-- what it does --> |

## Data Flow

<!-- Describe how data moves through the system. -->
<!-- Example: user request → API route → service layer → database → response -->
`;

// ── Artifact definitions ──────────────────────────────────────────────────────

interface ArtifactDef {
  id: ArtifactResult["id"];
  filename: string;
  canonicalFilename?: string;
  template: string;
}

const ARTIFACT_DEFS: ArtifactDef[] = [
  {
    id: "agents",
    filename: "AGENTS.generated.md",
    canonicalFilename: "AGENTS.md",
    template: AGENTS_TEMPLATE,
  },
  {
    id: "claude",
    filename: "CLAUDE.generated.md",
    canonicalFilename: "CLAUDE.md",
    template: CLAUDE_TEMPLATE,
  },
  {
    id: "validation-checklist",
    filename: "validation-checklist.generated.md",
    template: VALIDATION_CHECKLIST_TEMPLATE,
  },
  {
    id: "architecture-outline",
    filename: "architecture-outline.generated.md",
    canonicalFilename: "ARCHITECTURE.md",
    template: ARCHITECTURE_OUTLINE_TEMPLATE,
  },
];

// ── Token substitution ────────────────────────────────────────────────────────

function renderTemplate(
  template: string,
  tokens: Record<string, string>,
): string {
  let result = template;
  for (const [key, value] of Object.entries(tokens)) {
    result = result.replaceAll(`{{${key}}}`, value);
  }
  return result;
}

function buildTokens(projectPath: string, evidence: RepoEvidence): Record<string, string> {
  const projectName = basename(projectPath);
  const detectedLanguage = evidence.context.detectedLanguage;
  const detectedFramework = evidence.context.detectedFramework ?? "unknown";
  const generatedDate = new Date().toISOString().slice(0, 10);

  return {
    PROJECT_NAME: projectName,
    DETECTED_LANGUAGE: detectedLanguage,
    DETECTED_FRAMEWORK: detectedFramework,
    GENERATED_DATE: generatedDate,
  };
}

function selectedArtifactDefs(input: AuditInput): ArtifactDef[] {
  return ARTIFACT_DEFS.filter((def) => {
    if (def.id !== "claude") {
      return true;
    }

    return input.toolsResolved.includes("claude-code");
  });
}

// ── Guard check ───────────────────────────────────────────────────────────────

/**
 * Returns true if a canonical file exists (e.g. AGENTS.md), meaning the
 * generated file should be skipped entirely — no write attempt needed.
 * Used only for the canonical-file guard; the generated-file guard is
 * handled atomically via the `wx` write flag.
 */
function isCanonicalGuarded(projectPath: string, def: ArtifactDef): boolean {
  if (def.canonicalFilename) {
    return existsSync(join(projectPath, def.canonicalFilename));
  }
  return false;
}

/**
 * Returns true if either the generated file or canonical file already exists.
 * Used for dry-run / preview only — not for the actual write path.
 */
function isGuarded(projectPath: string, def: ArtifactDef): boolean {
  if (existsSync(join(projectPath, def.filename))) return true;
  return isCanonicalGuarded(projectPath, def);
}

// ── Main export ───────────────────────────────────────────────────────────────

/**
 * Generate starter artifact files for a project.
 *
 * When dryRun=true, computes content but does not write files (used for JSON
 * preview when --json is set without --write-artifacts).
 * When dryRun=false, applies overwrite guards and writes files to disk.
 */
export async function generateArtifacts(
  projectPath: string,
  evidence: RepoEvidence,
  input: AuditInput,
  dryRun: boolean,
): Promise<ArtifactResult[]> {
  const tokens = buildTokens(projectPath, evidence);
  const results: ArtifactResult[] = [];
  const artifactDefs = selectedArtifactDefs(input);

  for (const def of artifactDefs) {
    const content = renderTemplate(def.template, tokens);
    const targetPath = join(projectPath, def.filename);

    if (dryRun) {
      const guarded = isGuarded(projectPath, def);
      results.push({
        id: def.id,
        filename: def.filename,
        targetPath,
        skipped: guarded,
        written: false,
        content,
      });
      continue;
    }

    // Non-dry-run: only pre-check the canonical file (e.g. AGENTS.md).
    // The generated-file check is handled atomically via the wx flag below.
    const guarded = isCanonicalGuarded(projectPath, def);

    if (guarded) {
      process.stderr.write(
        `agent-harness: skipping ${def.filename} — file already exists\n`,
      );
      results.push({
        id: def.id,
        filename: def.filename,
        targetPath,
        skipped: true,
        written: false,
        content,
      });
      continue;
    }

    // Atomic write: O_CREAT | O_EXCL — fails with EEXIST if file was created
    // by another process between the canonical guard check above and now.
    try {
      await writeFile(targetPath, content, { encoding: "utf-8", flag: "wx" });
      results.push({
        id: def.id,
        filename: def.filename,
        targetPath,
        skipped: false,
        written: true,
        content,
      });
    } catch (err) {
      if ((err as NodeJS.ErrnoException).code === "EEXIST") {
        process.stderr.write(
          `agent-harness: skipping ${def.filename} — file already exists\n`,
        );
        results.push({
          id: def.id,
          filename: def.filename,
          targetPath,
          skipped: true,
          written: false,
          content,
        });
      } else {
        throw err;
      }
    }
  }

  return results;
}

/**
 * Returns computed artifact content without any filesystem checks or writes.
 * Used to populate the artifacts array in JSON output for dry-run preview.
 */
export function previewArtifacts(
  projectPath: string,
  evidence: RepoEvidence,
  input: AuditInput,
): ArtifactResult[] {
  const tokens = buildTokens(projectPath, evidence);
  return selectedArtifactDefs(input).map((def) => {
    const content = renderTemplate(def.template, tokens);
    const targetPath = join(projectPath, def.filename);
    const guarded = isGuarded(projectPath, def);
    return {
      id: def.id,
      filename: def.filename,
      targetPath,
      skipped: guarded,
      written: false,
      content,
    };
  });
}
